import pandas as pd
import numpy as np


# ============================================
# BASIC SALES SUMMARY
# ============================================

def get_sales_summary(df):
    """
    Calculate basic sales summary.

    Returns:
        Dictionary containing key sales metrics.
    """

    total_revenue = df["total_amount"].sum()

    total_orders = len(df)

    total_quantity = df["quantity"].sum()

    average_order_value = (
        total_revenue / total_orders
        if total_orders > 0
        else 0
    )

    return {
        "total_revenue": round(total_revenue, 2),
        "total_orders": int(total_orders),
        "total_quantity": int(total_quantity),
        "average_order_value": round(average_order_value, 2)
    }


# ============================================
# MONTHLY SALES
# ============================================

def get_monthly_sales(df):
    """
    Calculate monthly sales revenue.
    """

    data = df.copy()

    data["sale_date"] = pd.to_datetime(
        data["sale_date"],
        errors="coerce"
    )

    monthly_sales = (
        data.groupby(
            data["sale_date"].dt.to_period("M")
        )["total_amount"]
        .sum()
        .reset_index()
    )

    monthly_sales["sale_date"] = (
        monthly_sales["sale_date"]
        .astype(str)
    )

    monthly_sales = monthly_sales.rename(
        columns={
            "sale_date": "month",
            "total_amount": "revenue"
        }
    )

    monthly_sales["revenue"] = (
        monthly_sales["revenue"].round(2)
    )

    return monthly_sales


# ============================================
# SALES BY CATEGORY
# ============================================

def get_category_sales(df):
    """
    Calculate revenue generated by each category.
    """

    category_sales = (
        df.groupby("category")["total_amount"]
        .sum()
        .reset_index()
        .sort_values(
            by="total_amount",
            ascending=False
        )
    )

    category_sales = category_sales.rename(
        columns={
            "total_amount": "revenue"
        }
    )

    category_sales["revenue"] = (
        category_sales["revenue"].round(2)
    )

    return category_sales


# ============================================
# TOP PRODUCTS
# ============================================

def get_top_products(df, limit=10):
    """
    Find top products based on revenue.
    """

    product_sales = (
        df.groupby("product_name")
        .agg(
            revenue=("total_amount", "sum"),
            quantity_sold=("quantity", "sum"),
            orders=("product_name", "count")
        )
        .reset_index()
        .sort_values(
            by="revenue",
            ascending=False
        )
        .head(limit)
    )

    product_sales["revenue"] = (
        product_sales["revenue"].round(2)
    )

    return product_sales


# ============================================
# TOP CUSTOMERS
# ============================================

def get_top_customers(df, limit=10):
    """
    Find top customers based on total spending.
    """

    customer_sales = (
        df.groupby("customer_name")
        .agg(
            total_spent=("total_amount", "sum"),
            orders=("customer_name", "count"),
            quantity_purchased=("quantity", "sum")
        )
        .reset_index()
        .sort_values(
            by="total_spent",
            ascending=False
        )
        .head(limit)
    )

    customer_sales["total_spent"] = (
        customer_sales["total_spent"].round(2)
    )

    return customer_sales


# ============================================
# PAYMENT METHOD ANALYSIS
# ============================================

def get_payment_method_sales(df):
    """
    Analyze sales based on payment method.
    """

    payment_sales = (
        df.groupby("payment_method")
        .agg(
            revenue=("total_amount", "sum"),
            orders=("payment_method", "count")
        )
        .reset_index()
        .sort_values(
            by="revenue",
            ascending=False
        )
    )

    payment_sales["revenue"] = (
        payment_sales["revenue"].round(2)
    )

    return payment_sales


# ============================================
# DAILY SALES
# ============================================

def get_daily_sales(df):
    """
    Calculate daily sales revenue.
    """

    data = df.copy()

    data["sale_date"] = pd.to_datetime(
        data["sale_date"],
        errors="coerce"
    )

    daily_sales = (
        data.groupby("sale_date")["total_amount"]
        .sum()
        .reset_index()
        .sort_values("sale_date")
    )

    daily_sales["total_amount"] = (
        daily_sales["total_amount"].round(2)
    )

    return daily_sales


# ============================================
# BEST SELLING PRODUCTS
# ============================================

def get_best_selling_products(df, limit=10):
    """
    Find products with the highest quantity sold.
    """

    best_products = (
        df.groupby("product_name")["quantity"]
        .sum()
        .reset_index()
        .sort_values(
            by="quantity",
            ascending=False
        )
        .head(limit)
    )

    best_products = best_products.rename(
        columns={
            "quantity": "quantity_sold"
        }
    )

    return best_products


# ============================================
# CATEGORY PERFORMANCE
# ============================================

def get_category_performance(df):
    """
    Calculate revenue, quantity and orders
    for each product category.
    """

    category_performance = (
        df.groupby("category")
        .agg(
            revenue=("total_amount", "sum"),
            quantity_sold=("quantity", "sum"),
            orders=("category", "count")
        )
        .reset_index()
        .sort_values(
            by="revenue",
            ascending=False
        )
    )

    category_performance["revenue"] = (
        category_performance["revenue"].round(2)
    )

    return category_performance


# ============================================
# COMPLETE ANALYSIS
# ============================================

def analyze_sales_data(df):
    """
    Run all major sales analysis functions.

    Returns:
        Dictionary containing all analysis results.
    """

    results = {}

    results["summary"] = get_sales_summary(df)

    results["monthly_sales"] = get_monthly_sales(df)

    results["category_sales"] = get_category_sales(df)

    results["top_products"] = get_top_products(df)

    results["top_customers"] = get_top_customers(df)

    results["payment_methods"] = (
        get_payment_method_sales(df)
    )

    results["daily_sales"] = get_daily_sales(df)

    results["best_selling_products"] = (
        get_best_selling_products(df)
    )

    results["category_performance"] = (
        get_category_performance(df)
    )

    return results